services:
  data-proxy:
    container_name: scholar-data-proxy
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    volumes:
      - ${CACHE_HOST_DIR:-./cache_data}:/app/cache
    ports:
      - "${HOST_PORT:-37803}:${PORT:-37803}"
    restart: unless-stopped
